package lexer

const (
	TOKEN_UNKNOWN = iota
	TOKEN_NUMBER

	TOKEN_PLUS
	TOKEN_MINUS
	TOKEN_ASTERISK
	TOKEN_SLASH
	TOKEN_PERCENT
	TOKEN_CARET

	TOKEN_BRACE_LEFT
	TOKEN_BRACE_RIGHT

	TOKEN_EOF
)

type Token struct {
	Type int
	Raw  string
}

var TOKENS = map[int]string{
	TOKEN_UNKNOWN: "TOKEN_UNKNOWN",
	TOKEN_NUMBER:  "TOKEN_NUMBER",

	TOKEN_PLUS:     "TOKEN_PLUS",
	TOKEN_MINUS:    "TOKEN_MINUS",
	TOKEN_ASTERISK: "TOKEN_ASTERISK",
	TOKEN_SLASH:    "TOKEN_SLASH",
	TOKEN_PERCENT:  "TOKEN_PERCENT",
	TOKEN_CARET:    "TOKEN_CARET",

	TOKEN_BRACE_LEFT:  "TOKEN_BRACE_LEFT",
	TOKEN_BRACE_RIGHT: "TOKEN_BRACE_RIGHT",

	TOKEN_EOF: "TOKEN_EOF",
}
